# Netlify configuration for Japan Haul

[build]
  command = "npm run build"
  publish = ".next"
  environment = [
    "NEXT_PUBLIC_BASE_URL"
  ]

# API route specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
